---
- include: ../../openstack-ansible/playbooks/os-tempest-install.yml

- name: Add resource load to deployment
  hosts: utility_all[0]
  tasks:
    - name: Install virtualenv
      pip:
        name: "virtualenv"
    - name: Prepare a virtualenv for generate_resources.py
      pip:
        name: "{{ item }}"
        virtualenv: "{{ venv }}"
        extra_args: "--isolated"
      with_items:
        - "ipaddress==1.0.18"
        - "python-cinderclient==2.2.0"
        - "python-openstacksdk==0.5.2"
        - "python-novaclient==9.0.0"
        - "os-client-config==1.28.0"
    - name: Generate resources
      script: "../../scripts/generate_resources.py --servers {{ server_count }} --volumes {{ volume_count }} --networks {{ network_count }} --infinite-quotas --output-file /tmp/generated_resources.json"
      environment:
        OS_ENDPOINT_TYPE: "internalURL"
        OS_USERNAME: "admin"
        OS_PASSWORD: "{{ keystone_auth_admin_password }}"
        OS_PROJECT_NAME: "admin"
        OS_AUTH_URL: "{{ keystone_service_internalurl_v3 }}"
        OS_USER_DOMAIN_NAME: "Default"
        OS_PROJECT_DOMAIN_NAME: "Default"
        PATH: "{{ venv }}/bin"
    - fetch:
        src: "/tmp/generated_resources.json"
        dest: "/tmp/"
        flat: "yes"
    - name: Remove virtualenv
      file:
        path: "{{ venv }}"
        state: "absent"
  vars:
    venv: "/tmp/load_gen_venv"

- name: Add instance monitoring script
  hosts: hosts
  tasks:
    - name: Copy instance IP adddresses file to host
      copy:
        src: "/tmp/generated_resources.json"
        dest: "/etc/"
